export { default as Splash } from "./Splash"
export { default as ParentScreen } from "./ParentScreen"
export { default as Login } from "./Login"
export { default as Register } from "./Register"
export { default as WardScreen } from "./WardScreen"